import '../scss/styles.scss'
import imgLogo from '/images/logo.svg'
import imgChat from '/images/chat.svg'
import imgCheck from '/images/check.svg'
import imgPerson from '/images/person.svg'
import imgPhone from '/images/phone.svg'
import imgRepair from '/images/repair.svg'
import imgTopscreen from '/images/top-screen-image.jpg'
import imgArrowsdown from '/images/arrows-down.svg'
